version: "3.9"

services:
  sistema:
    image: webdevops/php-apache:8.4-alpine
    ports:
      - "8081:80"
    volumes:
      - ./app/:/app
    networks:
      - devops

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "projetodio_db"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - devops

volumes:
  db_data:

networks:
  devops:
    driver: bridge
